import java.io.FileInputStream
import java.util.Properties

plugins {
    id("com.android.application")
    id("kotlin-android")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
    id("com.google.gms.google-services")
}

// Load keystore properties
val keystorePropertiesStage = Properties()
val keystorePropertiesStageFile = rootProject.file("keyStage.properties")
if (keystorePropertiesStageFile.exists()) {
    keystorePropertiesStage.load(FileInputStream(keystorePropertiesStageFile))
}

val keystorePropertiesProd = Properties()
val keystorePropertiesProdFile = rootProject.file("keyProd.properties")
if (keystorePropertiesProdFile.exists()) {
    keystorePropertiesProd.load(FileInputStream(keystorePropertiesProdFile))
}

android {
    namespace = "dev.mhmz.lensfolio_mobile_app"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "dev.mhmz.lensfolio_mobile_app"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
        multiDexEnabled = true
    }

    signingConfigs {
        if (keystorePropertiesStageFile.exists()) {
            create("stage") {
                keyAlias = keystorePropertiesStage["keyAlias"] as String
                keyPassword = keystorePropertiesStage["keyPassword"] as String
                storeFile = keystorePropertiesStage["storeFile"]?.let { file(it) }
                storePassword = keystorePropertiesStage["storePassword"] as String
            }
        }
        if (keystorePropertiesProdFile.exists()) {
            create("prod") {
                keyAlias = keystorePropertiesProd["keyAlias"] as String
                keyPassword = keystorePropertiesProd["keyPassword"] as String
                storeFile = keystorePropertiesProd["storeFile"]?.let { file(it) }
                storePassword = keystorePropertiesProd["storePassword"] as String
            }
        }
    }

    buildTypes {
        debug {
            // Debug builds use default debug signing
        }
        release {
            // Release builds will use the signing config from the flavor
            // Signing is configured per flavor in flavorizr.gradle.kts
            signingConfig = null
        }
    }
}

flutter {
    source = "../.."
}

dependencies {
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
    implementation("com.google.android.material:material:1.13.0")
    implementation("androidx.multidex:multidex:2.0.1")
}

// ----- BEGIN flavorDimensions (autogenerated by flutter_flavorizr) -----
apply { from("flavorizr.gradle.kts") }
// ----- END flavorDimensions (autogenerated by flutter_flavorizr) -----